// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controllers

import (
	"github.com/google/wire"
	"sample/internal/usecases"
)

// Injectors from wire.go:

func NewUserController() UserController {
	userUsecase := usecases.NewUserUsecase()
	userController := UserController{
		userUsecase: userUsecase,
	}
	return userController
}

// wire.go:

var diUserUsecase = wire.Bind(
	new(UserUsecase),
	new(usecases.UserUsecase),
)

var userUsecaseSet = wire.NewSet(usecases.NewUserUsecase, diUserUsecase)
