// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package usecases

import (
	"github.com/google/wire"
	"sample/internal/repositories"
	"sample/internal/usecases/mock_usecases"
)

// Injectors from wire.go:

func NewUserUsecase() UserUsecase {
	userRepository := repositories.UserRepository{}
	userUsecase := UserUsecase{
		userRepo: userRepository,
	}
	return userUsecase
}

func NewMockUserUsecase(m *mock_usecases.MockUserRepo) UserUsecase {
	userUsecase := UserUsecase{
		userRepo: m,
	}
	return userUsecase
}

// wire.go:

var diUserRepo = wire.Bind(
	new(UserRepo),
	new(repositories.UserRepository),
)

var diMockUserRepo = wire.Bind(
	new(UserRepo),
	new(*mock_usecases.MockUserRepo),
)

var userRepoSet = wire.NewSet(wire.Struct(new(repositories.UserRepository), "*"), diUserRepo)
